#!/usr/bin/env python3

from email import send_mail
import random, string, sys

something_thats_forbidden_to_send = '''|>Y!G&vPBz:k-D;M+XO?%ERqZ<VS`j#A/KC*L@$,WwFTNU^~I\\JQ'''
something_thats_forbidden_to_send_backup = something_thats_forbidden_to_send

def menu():
    print("=====================================")
    print("=========== email kompani ===========")
    print("=====================================")
    print("[+] 1. choose email")
    print("[+] 2. send message")

def email():
    global something_thats_forbidden_to_send

    # generated by gpt : give me 5 made up company email 
    print()
    print("[!] which kompani email you want to send")
    print("[+] 1. jsmith@techglobe.com")
    print("[+] 2. amy.white@innovatebiz.net")
    print("[+] 3. david.miller@cyberwave.org")
    print("[+] 4. emma.jones@stellarcorp.co")
    print("[+] 5. john.doe@nexustechsolutions.com")
    rng = random.randint(1,5)
    inp = int(input(">> "))
   
    print()

    if inp == rng:
        enabled_char = set(something_thats_forbidden_to_send[random.randint(0,1000) % len(something_thats_forbidden_to_send)])
        something_thats_forbidden_to_send = ''.join(set(something_thats_forbidden_to_send) - enabled_char)
    else:
        something_thats_forbidden_to_send = something_thats_forbidden_to_send_backup

    return

def send():
    BLOCK = something_thats_forbidden_to_send + string.whitespace
    inp = input("message : ")

    if any(x for x in inp if x in BLOCK):
        print('\n[!] follow the rules sir\n')
        return
    
    if not inp.isascii():
        print('\n[!] we can\'t send that\n')
        return
    
    try:
        send_mail(eval(inp, {'__builtins__':None}))
    except:
        print("\n[!] sorry this function is not working somehow\n")

if __name__ == '__main__':
    while True:
        menu()
        try:
            inp = int(input(">> "))
            if inp == 1:
                email()
            elif inp == 2:
                send()
            else:
                sys.exit()
        except:
            print('!!! Please behave, we do not tolerate any violation to our system !!!')
            sys.exit()